# Generated by Django 3.0.3 on 2022-07-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200223_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
