# Generated by Django 4.0 on 2022-07-31 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='create_time',
            new_name='createTime',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='edit_time',
            new_name='editTime',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='html_doc',
            new_name='htmlDocument',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='md_doc',
            new_name='mdDocument',
        ),
    ]
