# Generated by Django 4.0 on 2022-07-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_fromorg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fromOrg',
            field=models.BooleanField(default=False),
        ),
    ]
